name: Yu test simple
run-name: Any name
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Python
        uses: actions/setup-python@v4

      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: SG60/setup-poetry@v1
      - run: poetry install          # you can use poetry now!

