name: Yu test simple
run-name: Any name
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4

      - name: Install Poetry
        uses: snok/install-poetry@v1
      - name: Poetry install
        run: poetry install
      - name: Run tests
        run: |
          source .venv/bin/activate
          pytest tests/ --junitxml report.xml --headless
      - name: Create test summary
        uses: test-summary/action@v2.0
        with:
          paths: report.xml
        if: always()
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          junit_files: "report.xml"
      #----------------------------------------------
      #              save report for download
      #----------------------------------------------
      - name: Upload report using artifacts
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: report
          path: /home/runner/work/Saucedemo_Yu/Saucedemo_Yu/report/
            
