name: Yu test simple
run-name: Any name
on: [push, pull request]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Poetry Install
        uses: knowsuchagency/poetry-install@v2
