name: Yu test simple
run-name: Any name
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out this repo
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
      - name: Poetry install
        run: poetry install
      - name: Run tests
        run: poetry run pytest

            
